[package]
name = "findfile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.11"
os_str_bytes = "6.5"
home = "0.5.5"
