so, ff has a lot of different literals. let's try to enumerate them and see how it goes

digits := DIGIT {DIGIT | '_'} ;
integer := digits | 0[xX][\da-fA-F_]+ | 0[oO][0-7_]+ | 0[bB][01_]+ ;
float := digits['.' digits][('e' | 'E')["+" | "-"]digits] ;
numeric := integer | float;

number := numeric ;
size-literal := numeric ++ unit-suffix ++ ['i' | 'I'] ++ ('b' | 'B') ;
unit-suffix := 'k' | 'K' | 'm' | 'M' | 'g' | 'G' | 't' | 'T' | 'p' | 'P' | 'e' | 'E' ;


env variables as:
	- strings: "$x"
	- regexes: $/$x/
	- 
